package com.TestProject;

public class Excaeption  {
	
	

	

	public static void main(String[] args) throws ArithmeticException  {
		
		
		// TODO Auto-generated method stub
		try {
			 int r=10/0;
			
		} catch (Exception e) {
			// TODO: handle exception
			System.out.println("Airthmatic excep[tion");
		}
        
		
		
		
		display();
		
		
		
			
			
}
	
	public static  void display() 
	{
	
		//int r=10/0;
		
		System.out.println("Airthmatic excep[tion");
	}

	}


